unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

set-option -g status-position top
set -g base-index 1
setw -g pane-base-index 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# Theme
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_transparent 1 # transparent background
set -g @tokyo-night-tmux_show_git 1             # local git status
set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
set -g @tokyo-night-tmux_show_netspeed 1        # network speed
#set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
#set -g @tokyo-night-tmux_show_music 1           # now playing
set -g @tokyo-night-tmux_show_path 1            # current path
set -g @tokyo-night-tmux_show_hostname 1        # machine hostname

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf
run '~/.tmux/plugins/tpm/tpm'
