unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

set-option -g status-position top
set -g base-index 1
setw -g pane-base-index 1

# Open new panes and windows with the same path as current pane
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Popup commands
bind C-g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "lazygit"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-l display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-y display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "yazi"

# Get Yazi image preview working in tmux
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# Theme
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_transparent 1 # transparent background
set -g @tokyo-night-tmux_show_git 1             # local git status
set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
#set -g @tokyo-night-tmux_show_netspeed 1        # network speed
#set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
#set -g @tokyo-night-tmux_show_music 1           # now playing
set -g @tokyo-night-tmux_show_path 1            # current path
#set -g @tokyo-night-tmux_show_hostname 1        # machine hostname

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf
run '~/.tmux/plugins/tpm/tpm'
